[workspace]
authors = ["Neil Macneale V <neil.macneale.v@gmail.com>", "Pierce Coyle <coylep2@wwu.edu>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "ur3e"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
sim = "ros2 launch ros_robotiq_description ur3e_sim.launch.py"
sim-yolo = "ros2 launch ros_robotiq_description ur3e_YOLO.launch.py spawn_z:=0.9652"
sim-depth = "ros2 launch ros_robotiq_description ur3e_depth.launch.py spawn_z:=0.9652"
sim-eyeinhand = "ros2 launch ros_robotiq_description ur3e_depth.launch.py spawn_z:=0.9652 world:=$PIXI_PROJECT_ROOT/src/ros_robotiq_description/ros_robotiq_description/worlds/table_world.sdf"
sim-calibration = "ros2 launch ros_robotiq_description ur3e_depth.launch.py spawn_z:=0.9652 world:=$PIXI_PROJECT_ROOT/src/ros_robotiq_description/ros_robotiq_description/worlds/calibration_world.sdf"

build = "colcon build --symlink-install"
node-list = "ros2 node list"
topic-list = "ros2 topic list"
gz-list = "gz topic -l"
image-view = "ros2 run rqt_image_view rqt_image_view"
graph = "rqt_graph"

[activation.env]
GZ_SIM_RESOURCE_PATH = "$GZ_SIM_RESOURCE_PATH:$PIXI_PROJECT_ROOT/src/models:$PIXI_PROJECT_ROOT/src/oakd_gazebo/oakd_gazebo/models:$PIXI_PROJECT_ROOT/install/oakd_description/share"


[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
filelock = ">=3.20.0,<4"
setuptools = "<=70.8.0"
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-xacro = ">=2.0.11,<3"
ros-jazzy-ur-description = ">=3.0.1,<4"
ros-jazzy-robotiq-description = ">=0.0.1,<0.0.2"
ros-jazzy-gz-sim-vendor = ">=0.0.8,<0.0.9"
ros-jazzy-ros-gz = ">=1.0.16,<2"
ros-jazzy-ros2-control = ">=4.33.0,<5"
ros-jazzy-moveit = ">=2.12.3,<3"
make = ">=4.4.1,<5"
compilers = ">=1.11.0,<2"
ros-jazzy-gz-ros2-control = ">=1.2.14,<2"
ros-jazzy-ros2-controllers = ">=4.28.0,<5"
ros-jazzy-rqt-graph = ">=1.5.4,<2"
ros-jazzy-rqt-image-view = ">=1.3.0,<2"
ros-jazzy-image-pipeline = ">=5.0.11,<6"
ros-jazzy-pcl-ros = ">=2.6.2,<3"

[pypi-dependencies]
ultralytics = ">=8.4.11, <9"
