apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.10
    max_hamming: 0
    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    pose_estimation_method: "pnp"
    tag:
      ids:    [20]
      frames: ["tag_20"]
      sizes:  [0.10]
