# Joints limits
#
# Sources:
#
#  - UR3 User Manual, Universal Robots, UR3/CB3, Version 3.13
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69300/99241_UR3_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    min_position: -6.283185307179586
    max_position:  6.283185307179586
    max_velocity:  3.141592653589793
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    min_position: -6.283185307179586
    max_position:  6.283185307179586
    max_velocity:  3.141592653589793
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    min_position: -3.141592653589793
    max_position:  3.141592653589793
    max_velocity:  3.141592653589793
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 9.0
    min_position: -6.283185307179586
    max_position:  6.283185307179586
    max_velocity:  6.283185307179586
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    min_position: -6.283185307179586
    max_position:  6.283185307179586
    max_velocity:  6.283185307179586
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: false
    has_velocity_limits: true
    max_effort: 12.0
    max_velocity:  6.283185307179586

  robotiq_85_left_knuckle_joint:
    has_position_limits: false
    min_position: 0.0
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
